### ISSUE TITLE
Added flexibility in AWSS3Resolver

### ISSUE THREAD

**Issue by jweisman** [medusa-project/cantaloupe#103]
Hi there. We'd like to use the AWSS3Resolver but in order to work in our deployment topology we've had to make 2 changes:

1. Use a `CredentialProviderChain` to take the credentials from other environment parameters if not specified in the properties file
2. Allow the `get_s3_object_key` delegate method to return an array with the bucket name and key for cases where the bucket can't be hard coded in the properties file

Would you be open to considering a pull request with these changes?

**Comment by adolski** [comment]
Hi, thanks for offering this!

> Use a CredentialProviderChain to take the credentials from other environment parameters if not specified in the properties file

I get the motivation for this and I agree that it's useful, but I would like to figure out a way to make this sort of "falling back to the environment" work globally across config keys, not just on a couple of specific ones, because it could be useful for some other resolvers and caches, and maybe other things too.

> Allow the get_s3_object_key delegate method to return an array with the bucket name and key for cases where the bucket can't be hard coded in the properties file

This one sounds great, but instead of an array, could you return a hash with `'key'` and `'bucket_name'` keys? (Probably `'bucket_region'` too, but I can add that if you don't.)
