### ISSUE TITLE
Access control (authorized delegate) questions...

### ISSUE THREAD

**Issue by devanonyme** [medusa-project/cantaloupe#108]
Hello,

We are using the acl delegate and I would have two question related to it's use :

  def self.authorized?(identifier, full_size, operations, resulting_size,
                       output_format, request_uri, request_headers, client_ip,
                       cookies)

1) While looking at Cantaloupe source I had found that client_ip was actually taking in account the presence of x-forwarded-for and the stack nature of it (getCanonicalClientIpAddress) and tought we could use this value to get the source client ip (we use the proxy). But the current value we get is :0:0:0:0:0:0:0:1. My coworker have used request_headers["x-forwarded-for"] wich does return the right value (my own ip by exemple 10.x.x.x).

I guess we should investigate where this value is comming from but is this the expected behavior? Should we reimplement the handling of possible x-forwarded stack headers in the script?

2) We also use the fileSystemResolver with a remote service and this service is basically the same service that implements the ACL. I have considered the option of using only the fileSystemResolver to spare the double call but the script is not injected with client_ip information. Is this a scenario that was considered or would be considered a bad practice from security standpoint?

Thanks for any help!

**Comment by devanonyme** [comment]
About #1, I did some more investigation (cantaloupe standalone + two proxy with node.js node-http-proxy to make sure I get a chain of forwarded-for headers)

It looks like forwardedIps is always empty but I was able to see the x-forwarded headers and origin client ip with getUpstreamAddress and looking at the content of getHeaders();

![exemple_xforwarded](https://cloud.githubusercontent.com/assets/21067311/25763297/64e311fe-31b0-11e7-8e1f-9989d1739287.png)


```
        final String upstreamAdress = getRequest().getClientInfo().
                getUpstreamAddress();
        Map<String,String> current_headers = getRequest().getHeaders().getValuesMap();
```
I tought the problem was a missing flag (see https://restlet.com/open-source/documentation/javadocs/2.2/jse/api/org/restlet/data/ClientInfo.html#getForwardedAddresses() ) but I have added the configurations and it doesnt look like it solve the issue.

```
                HttpConfiguration httpConfig = new HttpConfiguration();
                **httpConfig.addCustomizer( new ForwardedRequestCustomizer());
                HttpConnectionFactory connectionFactory = new HttpConnectionFactory( httpConfig );**
                ServerConnector connector = new ServerConnector(server, connectionFactory);
```
I'll continue the investigation later...

**Comment by adolski** [comment]
Sorry about the delay on this one --

1. `client_ip` is supposed to be a best guess at the user agent's IP, taking into account the `X-Forwarded-For` header if available. But I see that it's not working that way. The Restlet ClientInfo methods (getForwardedAddresses(), getUpstreamAddress(), etc.) aren't working like I expect. I made a manual fix (above) that ought to take care of this.

2. `get_pathname()` is only meant to translate identifiers to pathnames and not to evaluate authorization. That's in order to keep the implementation simple and isolate lookup logic from auth logic. But, I can certainly see how that trades away efficiency when lookups have to be repeated.

I don't think a solution is necessarily as simple as merging lookup and auth logic because there may be other delegate methods that need to do their own service requests as well.

This was one of the reasons for the delegate method cache (`delegate_script.cache.enabled`). But it's not a perfect solution, and I can't really think of one. Maybe some other caching would be possible, in Ruby and/or the HTTP layer. Or maybe redesigning the delegate system somehow, to merge all of the methods together, or pass all of the arguments to a delegate object constructor or something. (?)

P.S. thanks again for reporting these issues and investigating them so thoroughly -- it's a huge help.
