### ISSUE TITLE
Using Nearest Neighbor resampling

### ISSUE THREAD

**Issue by Eyal-R** [medusa-project/cantaloupe#122]
Hello,

I'm trying to push Cantaloupe's performance better - I was wondering how can you use Nearest Neighbor algorithm for resampling, it's not in the allowed list of values in the configuration: 

```
# Available values are `bell`, `bspline`, `bicubic`, `box`, `hermite`,
# `lanczos3`, `mitchell`, `triangle`.
# These are used only by FfmpegProcessor, Java2dProcessor, OpenJpegProcessor,
# and PdfBoxProcessor.
processor.downscale_filter =
processor.upscale_filter =
```

(I'm using JAI processor)

Thanks!
Eyal

**Comment by adolski** [comment]
Hi,

Those config keys don't currently apply to JaiProcessor. For downscaling it uses JAI's [SubsampleAverage](https://docs.oracle.com/cd/E17802_01/products/products/java-media/jai/forDevelopers/jai-apidocs/javax/media/jai/operator/SubsampleAverageDescriptor.html) operator and for upscaling it uses [Scale](http://docs.oracle.com/cd/E17802_01/products/products/java-media/jai/forDevelopers/jai-apidocs/javax/media/jai/operator/ScaleDescriptor.html).

`Scale` works in conjunction with an [Interpolation](http://docs.oracle.com/cd/E17802_01/products/products/java-media/jai/forDevelopers/jai-apidocs/javax/media/jai/Interpolation.html) instance, but output quality with all of the out-of-the-box implementations is poor (which is why `SubsampleAverage` is used instead for downscaling [it doesn't support upscaling]). The nearest-neighbor implementation in particular produces aliasing so severe that I didn't even bother exposing it as an option.

It's possible to write custom interpolations, so maybe that would be an option at some point.
