### ISSUE TITLE
Authorization information to resolver delegate

### ISSUE THREAD

**Issue by jonathangreen** [medusa-project/cantaloupe#137]
First I just have to say Cantaloupe is an awesome image server, and I really appreciate all the work that has gone into it. 

I'm having a bit of a problem with my authorization workflow. I am implementing an authorization delegate which verifies a username and password that is passed in with the request headers. So far this is all okay. 

However this username and password information also needs to be included in the HTTP request to the backend using the `HttpResolver`. I was hoping I would be able to sort out this information in the `ScriptLookupStrategy ` delegate, but it doesn't seem to have any access to headers.

My question is: Is there any way that I am missing to pass information from the authorization delegate to the HttpResolver delegate, or is there any way to get access to headers in the HttpResolver delegate? 

If the answer to the above questions is no, would there be any interest in a PR that implemented functionality to pass some sort of an opaque auth object between the authorization delegate and the resolver delegates.

Thanks!

**Comment by adolski** [comment]
Yeah, that isn't going to work, currenly. I think the way I'd want to accomplish it would be to add the same arguments that are passed to `authorized?()` to `HttpResolver::get_url()`. Except, I'd probably want to pass them as a hash, so the method signature would look like: `get_url(identifier, context = {})`

I'd also want to do this for all the other resolvers' lookup methods, so that they can share in the fun.

How does that sound? Would that fit this use case?

**Comment by jonathangreen** [comment]
That would work for me for sure. Thanks so much for the response. 

I wanted to be able to pass some context between the delegates because it takes a database lookup to verify things in the `authorization delegate` and I will need to do the same db lookup in the  `ScriptLookupStrategy` delegate to get the information I need to pass to the backend. Its totally possible to do the DB query twice, so your solution would work for me. Its just a bit less efficient.

**Comment by adolski** [comment]
I understand about the inefficiency. One of the reasons for my counterproposal is that `authorized?()` as currently designed has to be called *after* `get_url()` because it takes a `full_size` argument which a resolver is needed to acquire. But, there are other challenges, too.

(I'm not completely happy with the way the delegate script is currently designed, mainly because it doesn't accommodate situations like this very well, and maybe some day it gets redesigned as a class that gets instantiated once per request, or something.)

I would welcome a pull request for this. I will just outline the steps I would envision if I were doing it myself. But, I'm open to other ideas, and don't feel obligated to do all or even any of this:

1. Add `e.i.l.c.resource.RequestContext` with accessors for all the arguments that get passed to `authorized?()` except `full_size`
2. Add `Resolver.setRequestContext(RequestContext)` (implementation could go in `AbstractResolver`)
3. Have the endpoints (`e.i.l.c.v1.ImageResource`, `e.i.l.c.v1.InformationResource`, `e.i.l.c.v2.ImageResource`, `e.i.l.c.v2.InformationResource`) build a RequestContext and pass it via the above method to the resolver they instantiate
4. The resolver passes its RequestContext into its delegate method call
5. Update the resolver tests
6. Update `HttpResolver.get_url()` in `delegates.rb.sample` to reflect the new argument
7. Update user manual
8. Add to `website/changes.html`
