### ISSUE TITLE
Should put() close the tempFile if exception is thrown?

### ISSUE THREAD

**Issue by jcoyne** [medusa-project/cantaloupe#156]
https://github.com/medusa-project/cantaloupe/blob/master/src/main/java/edu/illinois/library/cantaloupe/cache/FilesystemCache.java#L948

Our tomcat is occasionally hitting `org.apache.tomcat.jni.error: Too many open files`.  Prior to this we are seeing a number of `Unable to create directory` exceptions (see #154).  I'm wondering if this file ever gets closed when this happens?

**Comment by adolski** [comment]
Hi @jcoyne,

Have you been able to diagnose this open files issue? Is it caused by Cantaloupe? Does `lsof` show anything interesting?

I wonder if that IOException is related, or just coincidental, because the only opening of a file that happens in `put()` would be done internally by `FileUtils.writeStringToFile()`, which would open `tempFile` for writing and then close it on success or failure. I don't think it would ever leave it open, and I don't see any other leaks there. That's not to say there aren't any somewhere else, but maybe this is a false lead.

**Comment by jcoyne** [comment]
@adolski I haven't seen this since #154 has been fixed, but we also changed some Tomcat configuration, so it's hard to narrow it down to one issue in particular. Either way, it's no longer a problem.
