### ISSUE TITLE
PDFBox - Error converting to JPG

### ISSUE THREAD

**Issue by FrancoisPaquette** [medusa-project/cantaloupe#163]
Hi,

I'm having issues with some of our PDF, those with more complex artworks.  After trying to convert them into JPG, the connexion is closed after about 1 minute. Here's an exemple:

https://www.dropbox.com/s/ytwtuy6mju0y0qd/82812_20100102V-001-001.pdf?dl=0

I'm able to to convert them by desconstructing the artwork.  For exemple, if you look at the bottom of this file, you will see that I have removed some of the images and quite a lot of lines.

https://www.dropbox.com/s/59c4k6f0stxk3vy/test6.pdf?dl=0

Is it something you have seen before?

I tried converting the original PDF just using the PDFBox Library (version 2.0.7) and it is working, it takes about 30 secondes. Is it this version that you are using in Cantaloupe or the previous one?

Thanks!

**Comment by adolski** [comment]
Hi,

Cantaloupe has been using PDFBox 2.0.4 since version 3.3. This PDF does convert pretty accurately for me, although it takes 62 seconds on my laptop to get a 1:1 image at 150 dpi.

I tried upgrading to 2.0.7 locally, with a similar result. I believe `PDFRenderer.renderImageWithDPI()` (part of PDFBox) is just having a hard time with this particular PDF.

Looking into it further, it looks like the slowness is the result of adopting a different (slower) color conversion library in Java 8. [Here is the bug for that.](https://bugs.openjdk.java.net/browse/JDK-8041125) [This recommendation](https://stackoverflow.com/a/37727921/177529) to add the `-Dsun.java2d.cmm=sun.java2d.cmm.kcms.KcmsServiceProvider` VM option cuts the render time down to 3 seconds for me. I'm not sure if it would have negative (or positive) effects on other components that use Java 2D, though.

As a last resort, ImageMagickProcessor and GraphicsMagickProcessor can both handle PDF, if your IM/GM can.

As for the connection closing, I"m not sure about that, but could it be a proxy timeout?

**Comment by FrancoisPaquette** [comment]
It is indeed speeding up the process using the recommendation. 

I'm seeing the JDK is using a previous version of the conversion library (LittleCMS, v2.7). It will be upgraded to 2.8 in a short while, in January it looks like. 

https://bugs.openjdk.java.net/projects/JDK/versions/19043

Going through the bugs fixes on the Github, I am not seeing anything related but maybe it is going to help out. I’ll give it a try when it’s available and let you know.

As for the timeouts, I had the same behavior (I’m using a linux server) with tifs who were not tiled and thus, Jai wasn’t able to process them. I tried adding different parameters to the proxy to keep the connection open but it didn’t work. Anyhow, I do not want end users to wait that long so I didn’t investigate further that approach.

Thanks
