### ISSUE TITLE
Question about image size

### ISSUE THREAD

**Issue by gigamorph** [medusa-project/cantaloupe#196]
Hello, I'm about to pilot a science project and wondering if Cantaloupe has any inherent upper limit to the size of images it can handle. We are expecting our repository to contain many images of sizes ranging from 1GB to 10GB, probably in pyramidal TIFF or some other format. It would be perfect if someone has actually dealt with such requirements and can share his/her experience. Thank you.

**Comment by adolski** [comment]
Hi @gigamorph,

On the [home page](https://medusa-project.github.io/cantaloupe/), there is a demo of Cantaloupe serving tiles from a 6.2 GB pyramidal tiled BigTIFF. That's a real demo with an actual Cantaloupe instance behind it. The server is a single basic VM with 2 vCPUs. The TIFF image is hosted on the local filesystem and Cantaloupe's derivative cache is using an Amazon S3 bucket.

I'm sure that it could go bigger, but I don't know how much. Theoretically the size of the TIFF shouldn't matter much, because the tile size is the same at every pyramid level.

**Comment by gigamorph** [comment]
Ah, that sounds promising. Forgive my ignorance but are you implying if the format is something other than pyramidal TIFF or JPEG2000 the size overhead will grow much quicker? Also, I'm curious that the demo stores the source locally and use S3 for derivative cache. I'd have imagined it would normally be the other way around. Is it generally recommended to have remote caches?

**Comment by adolski** [comment]
> Ah, that sounds promising. Forgive my ignorance but are you implying if the format is something other than pyramidal TIFF or JPEG2000 the size overhead will grow much quicker?

Yes -- see [here](https://medusa-project.github.io/cantaloupe/manual/3.4/images.html)

> Also, I'm curious that the demo stores the source locally and use S3 for derivative cache. I'd have imagined it would normally be the other way around. Is it generally recommended to have remote caches? Thank you so much for your answer.

Maybe more information than you wanted, but:

The way that pyramidal tiled TIFF and JP2 maintain efficiency at large sizes is by enabling a reader to find out the positions of the (small amounts of) data it has to read within a file, and seek directly to them. With a format like JPEG, that isn't possible because the whole image is a big compressed blob. But with PT TIFF, the reader just has to read the header and then do some calculations to figure out what subimage to seek to, where it is, which tiles to read from it, where they are, etc. (JP2 is much more sophisticated but it's the same principle of selective decoding.)

This is all possible using the POSIX filesystem functions, but a service like S3 doesn't support those. All it can offer (*) is a stream of the whole file... which is a problem when the whole file is 6.2 GB. So the file either needs to be downloaded to the filesystem in advance (this is the "source cache" feature in Cantaloupe), or streamed in its entirety from S3 upon each request. But, not all processors are able to read from streams. Neither solutions are ideal, and the larger the image size, the less ideal they get.

(*) In time, it may be possible to overcome all of this with a seekable stream implementation that exploits the HTTP `Range` header. Until then, better to put large images on the filesystem.

----

For caching, the derivatives are mostly small JPEGs, so it doesn't matter as much where they're stored. S3 isn't super fast, but it's cheaper than a filesystem in AWS.

**Comment by gigamorph** [comment]
@adolski Many thanks for the kind explanation. It helps me a lot.
