### ISSUE TITLE
Resolver / auth in Java

### ISSUE THREAD

**Issue by eroux** [medusa-project/cantaloupe#197]
We are planning to use Cantaloupe for our image server. We already have some code in Java for the rest of our platform, and would like to ask if it would be possible to use Java directly for the resolvers/auth. I acknowledge that the ruby scripts can make some java calls, but:
- that adds an unnecessary level of complexity (Java -> Ruby -> Java)
- that prevents us from caching data from one call to another (there would be calls to another REST API at each auth and fetch, independant from the actual image fetching, and these could be cached)

Other projects (like the Luce integration in Jena/Fuseki, see [here](https://jena.apache.org/documentation/query/text-query.html#generic-and-defined-analyzer-support)) allow passing a class path in the configuration, where the referenced class is a subclass of something known to the application.

It would be helpful for us if Cantaloupe allowed the same feature, so the configuration file would hold something like:

```
resolver.custom="io.bdrc.cantaloupe.Resolver"
atuh.customclass="io.bdrc.cantaloupe.Auth"
```

and each class would be instanciated only once per run of Cantaloupe. Would that make sense? We are ready to produce the code to allow that if that's the case.

**Comment by eroux** [comment]
I guess it's an elaboration on https://github.com/medusa-project/cantaloupe/issues/95

**Comment by adolski** [comment]
Hi @eroux,

Currently all of the Java API should be considered private. There are a lot of questions around a plugin-type mechanism (#95), and if happens, I think I'll still prefer to keep most internal API private and instead offer some kind of plugin interface, because I enjoy not having to respect any contracts internally.

It's true that the Ruby-Java bridge involves a performance penalty, but, if you haven't already, I'd encourage you to measure the penalty exactly before writing it off. Most of what happens in the delegate methods is waiting on I/O, and I assume that you are thinking of caching as a reaction to the anticipated cost of that I/O, and thinking of shared resolver and auth instances as a way to do caching (?). But there are other ways, too:

* Enable the built-in delegate method invocation cache (DMIC);
* Instantiate a shared ConcurrentHashMap in Ruby, or even a [Caffeine cache](https://github.com/ben-manes/caffeine) (this is one of Cantaloupe's dependencies and should also be considered private API, but there's nothing stopping you, although the DMIC is backed by one of these to begin with);
* Especially if you expect to be running a cluster of image servers at some point, it might be better to move the caching outside of the image server, perhaps into a microservice, so that all nodes can benefit from a shared cache.

Just throwing some ideas out there.

I notice that you've already seen the issue for the delegate script redesign (#148) -- this will address the problem of sharing data between methods. When it's ready, the migration should be pretty easy and I expect the contract for the new version to be at least as stable as the current one. OTOH, if Cantaloupe's Java API had been exposed all along it would be on version 22.4 by now. :smile:

**Comment by eroux** [comment]
Ok, closing the issue, we will most likely move to another iiif server. Cantaloupe seems to focus on use cases that are too different from ours. Thank you!
