### ISSUE TITLE
Cantaloupe with the IIIF Authentication API

### ISSUE THREAD

**Issue by jweisman** [medusa-project/cantaloupe#214]
We are looking at implementing the [IIIF Authentication API](http://iiif.io/api/auth/1.0/). According to my reading of the API, it expects the info.json request to respond with a 401 to trigger the authentication flow. It also passes an `Authorization: Bearer` token to the info.json request to facilitate previously negotiated authentication. However Cantaloupe doesn't invoke the `authorized?` delegate method for information requests so I'm not sure if this can be done.

Do you have any thoughts/advice on integrating Cantaloupe with the Authentication API? Thanks.

**Comment by adolski** [comment]
The authorization mechanism currently isn't Auth API-aware. I haven't even read the spec yet. I probably should pretty soon, though.

In the meantime I guess this would need to be handled in another HTTP tier.

**Comment by jweisman** [comment]
Thanks for the response. Would you be willing to consider a PR to authorize information requests (by configuration perhaps)? Or is that something you’re trying to avoid?

**Comment by adolski** [comment]
I don't have time to dig into the Auth API right now, but do you have a rough idea of what kind of changes would be needed to conform? If adding the image endpoints' protection to the information endpoints is all that's needed, that seems like it would be a straightforward & reasonable thing to do. I don't remember offhand why it doesn't already work that way -- maybe something to do with performance -- but I'm fine with protecting them.

But, if more substantial changes will be needed, then I'd like to wait until I have time to consider this more thoroughly, because I'm not completely happy with how the current auth system works, and maybe it would be best to roll Auth API into a larger overhaul.

**Comment by jweisman** [comment]
Thanks- I think we'll leave this for now and try to find a solution outside of Cantaloupe.
