### ISSUE TITLE
Ideas for pre warming the cache to reduce initial load times?

### ISSUE THREAD

**Issue by coreymead** [medusa-project/cantaloupe#239]
I've got a deployment of Cantaloupe in amazon that uses an S3source with a Filesystem Cache.  Anytime a manifest is loaded into an image viewer like Medusa, it takes about 5-10 seconds for the image to load.  I was wondering if anyone knew of a way to pre warm the cache when my instance boots up so that we don't have these long initial load times.  Obviously I could write something to make calls to all of the images in my S3 bucket, but I'm curious if there are more elegant solutions that I'm not thinking of.  The instance is in an ASG so that I can scale to add more servers if that matters.

Thanks!

**Comment by adolski** [comment]
There is no such caching feature built in. This would have to be accomplished by requesting in advance all of the tiles that the viewer could request.

But, a 5-10 second load time sounds pretty bad, and maybe indicative of a suboptimal configuration, but I'd need more info to say.

**Comment by bonaventure** [comment]
Our configuration and general strategy is in this repository (https://github.com/bonaventure/nins-cantaloupe-image-server). I'd be in your debt if you could take a peak and offer possible configuration improvements. I'm not sure if we need more memory/processor resources, or if we need to change our Cantaloupe configuration.

**Comment by adolski** [comment]
What kind of images are you serving that are slow? Format, typical dimensions & byte size?

**Comment by bonaventure** [comment]
We have two formats, we tried both with little improvement. 
1) Roughly 4500px x 6000px JPG images, which are about 12-20MB, depending on the color and detail. 
2) The original TIFs, so the same dimensions (4500-ish x 6000-ish), and the file sizes range from 60MB to 100MB per image.

**Comment by adolski** [comment]
Are the TIFFs pyramidal+tiled?

(See JPEG and TIFF sections [here](https://medusa-project.github.io/cantaloupe/manual/4.0/images.html#Source%20Formats))

**Comment by giancarlobi** [comment]
@bonaventure my 2 "eurocents" : my experience is very good using Cantaloupe with Jpeg2000 format, I have TIFF as original one and also jpeg2000 derived from TIFF and I use this last one to be rendered by Cantaloupe+Openseadragon. See this [example](http://asa.archiviostudiadriatici.it/islandora/object/cartea:2) : original TIFF 360MB and JP2 190MB -> time to load less than a second.
You can find [here](http://dev.digibess.it/doku.php?id=reloaded) our Cantaloupe settings (at the end of page)

**Comment by bonaventure** [comment]
@giancarlobi, what did you use to convert your TIFFs? And what size tiles did you find most effective?

**Comment by giancarlobi** [comment]
@bonaventure I use a bash script and this command 
`kdu_compress -i image.tif -o image.jp2 Creversible=yes -rate -,1,0.5,0.25 Clevels=5`
This is what Islandora suggests for TIFF to JP2 conversion and the result is the link above. To install kdu_compress see [here](http://dev.digibess.it/doku.php?id=reloaded:fe_itools). Also I use same command for tiff related to books as [this](http://www.byterfly.eu/islandora/object/libria:333)

**Comment by adolski** [comment]
Here's some good info on creating pyramidal tiled TIFFs: http://iipimage.sourceforge.net/documentation/images/

A big-picture difference between JP2 and PT TIFF is that JP2 provides a better compression ratio (and smaller file sizes) but is more computationally expensive--less so in the case of the commercial Kakadu codec and more so in the case of the free OpenJPEG.

If you opt for JP2, be careful with the arguments you pass to the encoder; for example, using `Clevels=5` with a large enough (dimensions) image will reduce decoding efficiency at small scales. It's best to use only the arguments you know you'll need, and let the compressor choose the rest itself, IMO.

**Comment by bonaventure** [comment]
@adolski Thank you for the clarification. Forgive my ignorance, but I'm still not exactly sure about the implications of tiles size. Is smaller better (so that a smaller tile is available if its needed)?
For example, I did the following conversion using VIPS, and chose 256x256 as the tile size:

`vips im_vips2tiff source.tif converted.tif:deflate,tile:256x256,pyramid`

Then I analyzed with tiffdump. When it comes to processing with Cantaloupe, what are the implications of tile size? 

`converted.tif:
Magic: 0x4949 <little-endian> Version: 0x2a <ClassicTIFF>
Directory 0: offset 80784748 (0x4d0ad6c) next 99562854 (0x5ef3566)
ImageWidth (256) SHORT (3) 1<6500>
ImageLength (257) SHORT (3) 1<6456>
BitsPerSample (258) SHORT (3) 3<8 8 8>
Compression (259) SHORT (3) 1<8>
Photometric (262) SHORT (3) 1<2>
Orientation (274) SHORT (3) 1<1>
SamplesPerPixel (277) SHORT (3) 1<3>
XResolution (282) RATIONAL (5) 1<236.22>
YResolution (283) RATIONAL (5) 1<236.22>
PlanarConfig (284) SHORT (3) 1<1>
ResolutionUnit (296) SHORT (3) 1<3>
TileWidth (322) SHORT (3) 1<256>
TileLength (323) SHORT (3) 1<256>
TileOffsets (324) LONG (4) 676<8 102160 202680 303402 404385 535332 664618 774752 884778 995602 1107469 1222472 1336219 1448152 1560208 1671852 1783902 1896906 2009076 2124348 2236955 2348156 2459337 2571183 ...>
TileByteCounts (325) LONG (4) 676<102152 100520 100722 100983 130947 129286 110134 110026 110824 111867 115003 113747 111933 112056 111644 112050 113004 112170 115272 112607 111201 111181 111846 113933 ...>
SampleFormat (339) SHORT (3) 3<1 1 1>
700 (0x2bc) BYTE (1) 5123<0x3c 0x3f 0x78 0x70 0x61 0x63 0x6b 0x65 0x74 0x20 0x62 0x65 0x67 0x69 0x6e 0x3d 0x22 0xef 0xbb 0xbf 0x22 0x20 0x69 0x64 ...>
33723 (0x83bb) LONG (4) 9<284 470024194 50354689 474424603 33554434 35390464 839385143 808661296 3748148>
ICC Profile (34675) UNDEFINED (7) 560<00 00 0x2 0x30 0x41 0x44 0x42 0x45 0x2 0x10 00 00 0x6d 0x6e 0x74 0x72 0x52 0x47 0x42 0x20 0x58 0x59 0x5a 0x20 ...>

Directory 1: offset 99562854 (0x5ef3566) next 104839276 (0x63fb86c)
SubFileType (254) LONG (4) 1<1>
ImageWidth (256) SHORT (3) 1<3250>
ImageLength (257) SHORT (3) 1<3228>
BitsPerSample (258) SHORT (3) 3<8 8 8>
Compression (259) SHORT (3) 1<8>
Photometric (262) SHORT (3) 1<2>
Orientation (274) SHORT (3) 1<1>
SamplesPerPixel (277) SHORT (3) 1<3>
XResolution (282) RATIONAL (5) 1<236.22>
YResolution (283) RATIONAL (5) 1<236.22>
PlanarConfig (284) SHORT (3) 1<1>
ResolutionUnit (296) SHORT (3) 1<3>
TileWidth (322) SHORT (3) 1<256>
TileLength (323) SHORT (3) 1<256>
TileOffsets (324) LONG (4) 169<80796138 80878377 80960132 81087253 81184971 81287143 81391021 81490366 81588796 81688551 81792725 81890371 81990881 82104409 82186920 82269245 82390184 82498306 82603726 82702088 82799498 82895340 82991275 83092087 ...>
TileByteCounts (325) LONG (4) 169<82239 81755 127121 97718 102172 103878 99345 98430 99755 104174 97646 100510 113528 82511 82325 120939 108122 105420 98362 97410 95842 95935 100812 94397 ...>
700 (0x2bc) BYTE (1) 5123<0x3c 0x3f 0x78 0x70 0x61 0x63 0x6b 0x65 0x74 0x20 0x62 0x65 0x67 0x69 0x6e 0x3d 0x22 0xef 0xbb 0xbf 0x22 0x20 0x69 0x64 ...>
33723 (0x83bb) LONG (4) 9<284 470024194 50354689 474424603 33554434 35390464 839385143 808661296 3748148>
ICC Profile (34675) UNDEFINED (7) 560<00 00 0x2 0x30 0x41 0x44 0x42 0x45 0x2 0x10 00 00 0x6d 0x6e 0x74 0x72 0x52 0x47 0x42 0x20 0x58 0x59 0x5a 0x20 ...>

Directory 2: offset 104839276 (0x63fb86c) next 106566814 (0x65a149e)
SubFileType (254) LONG (4) 1<1>
ImageWidth (256) SHORT (3) 1<1625>
ImageLength (257) SHORT (3) 1<1614>
BitsPerSample (258) SHORT (3) 3<8 8 8>
Compression (259) SHORT (3) 1<8>
Photometric (262) SHORT (3) 1<2>
Orientation (274) SHORT (3) 1<1>
SamplesPerPixel (277) SHORT (3) 1<3>
XResolution (282) RATIONAL (5) 1<236.22>
YResolution (283) RATIONAL (5) 1<236.22>
PlanarConfig (284) SHORT (3) 1<1>
ResolutionUnit (296) SHORT (3) 1<3>
TileWidth (322) SHORT (3) 1<256>
TileLength (323) SHORT (3) 1<256>
TileOffsets (324) LONG (4) 49<99570182 99640653 99752699 99848132 99936932 100032180 100120704 100219964 100294881 100408638 100519958 100631198 100743412 100852546 100968652 101043388 101154042 101261202 101368298 101477651 101584851 101699979 101775421 101898995 ...>
TileByteCounts (325) LONG (4) 49<70471 112046 95433 88800 95248 88524 99260 74917 113757 111320 111240 112214 109134 116106 74736 110654 107160 107096 109353 107200 115128 75442 123574 121801 ...>
700 (0x2bc) BYTE (1) 5123<0x3c 0x3f 0x78 0x70 0x61 0x63 0x6b 0x65 0x74 0x20 0x62 0x65 0x67 0x69 0x6e 0x3d 0x22 0xef 0xbb 0xbf 0x22 0x20 0x69 0x64 ...>
33723 (0x83bb) LONG (4) 9<284 470024194 50354689 474424603 33554434 35390464 839385143 808661296 3748148>
ICC Profile (34675) UNDEFINED (7) 560<00 00 0x2 0x30 0x41 0x44 0x42 0x45 0x2 0x10 00 00 0x6d 0x6e 0x74 0x72 0x52 0x47 0x42 0x20 0x58 0x59 0x5a 0x20 ...>

Directory 3: offset 106566814 (0x65a149e) next 107009334 (0x660d536)
SubFileType (254) LONG (4) 1<1>
ImageWidth (256) SHORT (3) 1<812>
ImageLength (257) SHORT (3) 1<807>
BitsPerSample (258) SHORT (3) 3<8 8 8>
Compression (259) SHORT (3) 1<8>
Photometric (262) SHORT (3) 1<2>
Orientation (274) SHORT (3) 1<1>
SamplesPerPixel (277) SHORT (3) 1<3>
XResolution (282) RATIONAL (5) 1<236.22>
YResolution (283) RATIONAL (5) 1<236.22>
PlanarConfig (284) SHORT (3) 1<1>
ResolutionUnit (296) SHORT (3) 1<3>
TileWidth (322) SHORT (3) 1<256>
TileLength (323) SHORT (3) 1<256>
TileOffsets (324) LONG (4) 16<104845644 104937969 105034850 105131974 105232868 105328907 105439159 105548556 105661950 105761452 105872300 105980732 106089483 106209985 106329016 106447697>
TileByteCounts (325) LONG (4) 16<92325 96881 97124 100894 96039 110252 109397 113394 99502 110848 108432 108751 120502 119031 118681 119117>
700 (0x2bc) BYTE (1) 5123<0x3c 0x3f 0x78 0x70 0x61 0x63 0x6b 0x65 0x74 0x20 0x62 0x65 0x67 0x69 0x6e 0x3d 0x22 0xef 0xbb 0xbf 0x22 0x20 0x69 0x64 ...>
33723 (0x83bb) LONG (4) 9<284 470024194 50354689 474424603 33554434 35390464 839385143 808661296 3748148>
ICC Profile (34675) UNDEFINED (7) 560<00 00 0x2 0x30 0x41 0x44 0x42 0x45 0x2 0x10 00 00 0x6d 0x6e 0x74 0x72 0x52 0x47 0x42 0x20 0x58 0x59 0x5a 0x20 ...>

Directory 4: offset 107009334 (0x660d536) next 107129332 (0x662a9f4)
SubFileType (254) LONG (4) 1<1>
ImageWidth (256) SHORT (3) 1<406>
ImageLength (257) SHORT (3) 1<403>
BitsPerSample (258) SHORT (3) 3<8 8 8>
Compression (259) SHORT (3) 1<8>
Photometric (262) SHORT (3) 1<2>
Orientation (274) SHORT (3) 1<1>
SamplesPerPixel (277) SHORT (3) 1<3>
XResolution (282) RATIONAL (5) 1<236.22>
YResolution (283) RATIONAL (5) 1<236.22>
PlanarConfig (284) SHORT (3) 1<1>
ResolutionUnit (296) SHORT (3) 1<3>
TileWidth (322) SHORT (3) 1<256>
TileLength (323) SHORT (3) 1<256>
TileOffsets (324) LONG (4) 4<106572918 106672422 106776402 106892386>
TileByteCounts (325) LONG (4) 4<99504 103980 115984 116947>
700 (0x2bc) BYTE (1) 5123<0x3c 0x3f 0x78 0x70 0x61 0x63 0x6b 0x65 0x74 0x20 0x62 0x65 0x67 0x69 0x6e 0x3d 0x22 0xef 0xbb 0xbf 0x22 0x20 0x69 0x64 ...>
33723 (0x83bb) LONG (4) 9<284 470024194 50354689 474424603 33554434 35390464 839385143 808661296 3748148>
ICC Profile (34675) UNDEFINED (7) 560<00 00 0x2 0x30 0x41 0x44 0x42 0x45 0x2 0x10 00 00 0x6d 0x6e 0x74 0x72 0x52 0x47 0x42 0x20 0x58 0x59 0x5a 0x20 ...>

Directory 5: offset 107129332 (0x662a9f4) next 0 (0)
SubFileType (254) LONG (4) 1<1>
ImageWidth (256) SHORT (3) 1<203>
ImageLength (257) SHORT (3) 1<201>
BitsPerSample (258) SHORT (3) 3<8 8 8>
Compression (259) SHORT (3) 1<8>
Photometric (262) SHORT (3) 1<2>
Orientation (274) SHORT (3) 1<1>
SamplesPerPixel (277) SHORT (3) 1<3>
XResolution (282) RATIONAL (5) 1<236.22>
YResolution (283) RATIONAL (5) 1<236.22>
PlanarConfig (284) SHORT (3) 1<1>
ResolutionUnit (296) SHORT (3) 1<3>
TileWidth (322) SHORT (3) 1<256>
TileLength (323) SHORT (3) 1<256>
TileOffsets (324) LONG (4) 1<107015342>
TileByteCounts (325) LONG (4) 1<113990>
700 (0x2bc) BYTE (1) 5123<0x3c 0x3f 0x78 0x70 0x61 0x63 0x6b 0x65 0x74 0x20 0x62 0x65 0x67 0x69 0x6e 0x3d 0x22 0xef 0xbb 0xbf 0x22 0x20 0x69 0x64 ...>
33723 (0x83bb) LONG (4) 9<284 470024194 50354689 474424603 33554434 35390464 839385143 808661296 3748148>
ICC Profile (34675) UNDEFINED (7) 560<00 00 0x2 0x30 0x41 0x44 0x42 0x45 0x2 0x10 00 00 0x6d 0x6e 0x74 0x72 0x52 0x47 0x42 0x20 0x58 0x59 0x5a 0x20 ...>
`

**Comment by adolski** [comment]
It's a balance. Tile sizes appear in `info.json` responses, so if your viewer respects those, you can visualize what's happening as it loads *n* tiles (more smaller tiles or fewer larger tiles, one HTTP request per tile) into a WxH viewport.

My guess is that 256 will be on the small side of optimal, but you may want to experiment with different sizes.
