### ISSUE TITLE
FilesystemCache - macOS detected on RHEL

### ISSUE THREAD

**Issue by FPaquette** [medusa-project/cantaloupe#244]
Hi,

I'm testing two Cantaloupe servers (3.4.4) using the same filesystemcache using a NFS link and I'm seeing this at startup :

13:40:20.526 [localhost-startStop-1] INFO  e.i.l.c.c.FilesystemCache - macOS detected; will use file last-modified times instead of last-accessed times.

Do you know what the implications would be, if any?

Thanks

**Comment by adolski** [comment]
Hi @FPaquette,

That message is being logged by mistake, and it's safe to ignore. This is fixed in 4.0.

Note the logger call with no surrounding logic:

https://github.com/medusa-project/cantaloupe/blob/4f6e86ddd9e898b747e50e1c5a04fe4353eb4a2a/src/main/java/edu/illinois/library/cantaloupe/cache/FilesystemCache.java#L601-L605
