### ISSUE TITLE
Cantaloupe 4.0.2 standalone stops responding when using HttpSource 

### ISSUE THREAD

**Issue by filak** [medusa-project/cantaloupe#248]
I have been testing CouchDB as HttpSource and it seems to be working:

HttpSource.BasicLookupStrategy.url_prefix = http://localhost:5984/images/

But after a short while Cantaloupe stops responding. I have 5 jp2 images displayed in OpenSeadragon viewer (small sized, the biggest is  10MB) and after minute(s) of zooming the tiles start being dropped.

Please see the [error-log.txt](https://github.com/medusa-project/cantaloupe/files/2561860/error-log.txt) excerpt.

What is interesting - when I use a reverse proxy in front of the backend, ie with Caddy:

couch.local {
    proxy / localhost:5984 {
        transparent
        keepalive 0
    }
}

HttpSource.BasicLookupStrategy.url_prefix = http://couch.local/images/

 the issue does not happen.

**Comment by adolski** [comment]
Sounds like either a Jetty or CouchDB issue.

The Jetty client used by HttpSource was updated in 4.0.2 after another user tracked down a [connection leak bug](https://github.com/medusa-project/cantaloupe/issues/232) in an earlier Jetty version. Unfortunately, because of that bug, I can't downgrade Jetty, and since the version in use is the newest available, I can't upgrade it either.

**Comment by filak** [comment]
It looks like so. There is something wrong with the communication between Jetty and CouchDB which is mitigated by the proxy. Or maybe with some other http backends...

Since there is a workaround and proxying CouchDB in production is preferable anyway I am closing this.
