### ISSUE TITLE
Add more timing-related log messages

### ISSUE THREAD

**Issue by hardyoyo** [medusa-project/cantaloupe#261]
A few methods which create log output including timing information, which is helpful for gathering performance metrics using a tool like Graylog to parse the application log. These methods include:

- SourceCacheDownload
- InfoService

There are other methods which generate log output that do not currently include timing information:

- ImageRepresentation
- TIFFImageReader
- DelegateProxy

ImageRepresentation would give us another metric with which we might evaluate changes we might make to the source cache (file system vs. s3). TIFFImageReader would  give us a metric to evaluate whether reading metadata from our images had any impact on performance. DelegateProxy would give us a metric to evaluate whether adding AuthN/Z to our service had any impact on performance.

Adding timing information to the log output for these methods should be fairly straightforward. As a newbie to Cantaloupe, I can try to do this myself. I thought I'd open this ticket first, to gather feedback on whether this information would be helpful to anyone else?

**Comment by adolski** [comment]
Hi @hardyoyo ,

> ImageRepresentation would give us another metric with which we might evaluate changes we might make to the source cache (file system vs. s3).

How does ImageRepresentation relate to the source cache? Are you looking to measure source cache I/O speed? SourceCacheDownload measures the writing component of that (which is probably usually limited by download speed) but I imagine that the reading component would be hard to do reliably.

(Also, the only available source cache is FilesystemCache -- there is no S3 option)

> TIFFImageReader would give us a metric to evaluate whether read metadata from our images had any impact on performance.

TIFFImageReader wraps an Image I/O TIFF reader which does not expose metadata-reading to its API as a discrete step, so its metadata-reading method(s) may return cached info and be un-timeable. If you are looking to measure a difference between two TIFF images, one containing X metadata and another containing Y (all TIFFs contain at least a baseline IFD) then results would probably be best obtained from this statement:

`DEBUG e.i.l.c.r.ImageRepresentation - Java2dProcessor processed in 13 msec`

Both the Image I/O reader and Cantaloupe should be trying to read only the IFDs they need to, so if an image has a lot of large sub-IFDs or whatever, then it shouldn't matter because of the way TIFF is structured, but the above log statement would be the way to verify.

> DelegateProxy would give us a metric to evaluate whether adding AuthN/Z to our service had any impact on performance.

DelegateProxy already logs all of its method calls with timing info included:

`DEBUG e.i.l.c.s.DelegateProxy - invokeUncached(): authorized? returned true for args: (none) in 1 msec`

**Comment by hardyoyo** [comment]
Ah, OK... so... it looks like you're already timing everything that makes sense to time. We'll proceed with parsing these values out using Graylog and use that information in our testing. Thanks!

Closing this issue.
