### ISSUE TITLE
Resolving

### ISSUE THREAD

**Issue by Eyal-R** [medusa-project/cantaloupe#43]
Hello,
Do you support the resolving of a URL identifier into a file path, using a SQL query to a table in a database?

Eyal

**Comment by adolski** [comment]
Yes. The basic idea would be to use the ScriptLookupStrategy of [FilesystemResolver](http://medusa-project.github.io/cantaloupe/manual/3.1/resolvers.html#FilesystemResolver). There is a code example in that section that shows the `get_pathname()` method querying Solr. This would need to be modified to query your database instead.

One thing to note is that database-specific Ruby gems won't work in JRuby because they use native extensions. Instead you'll need to install a JDBC driver for your database on the Java classpath, and use the `java.sql.*` package (from Ruby) to do the querying. Here is an example of a `get_pathname()` method using PostgreSQL:

```ruby
require 'java'

java_import 'org.postgresql.Driver'
java_import 'java.sql.DriverManager'

module Cantaloupe

  module FilesystemResolver

    JDBC_URL = 'jdbc:postgresql://localhost:5432/mydatabase'
    JDBC_USER = 'alexd'
    JDBC_PASSWORD = 'xxx'

    @@conn = DriverManager.get_connection(JDBC_URL, JDBC_USER, JDBC_PASSWORD)

    def self.get_pathname(identifier)
      begin
        sql = 'SELECT filename FROM item WHERE identifier = ? LIMIT 1'
        stmt = @@conn.prepare_statement(sql)
        stmt.set_string(1, identifier)
        results = stmt.execute_query
        results.next
        pathname = results.getString(1)
        return (pathname.length > 0) ? pathname : nil
      ensure
        stmt.close if stmt
      end
    end

  end

end

# Uncomment to test
# puts Cantaloupe::FilesystemResolver::get_pathname('my_image_identifier')

```

This is just a quick example; it is not well-tested and will need some adaptation for your database.

**Comment by Eyal-R** [comment]
Thanks a lot!
