### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by Ra1phM** [medusa-project/cantaloupe#50]
Hi, 

I was looking for an IIIF compatible image server and found this project. I really like it, you have done a great job.

I didn't find any details concerning the road map or the future plans for this project. Could you share some details about it? 

I am really interested and intend to use such an image server in a production environment in the near future.

Thanks

**Comment by adolski** [comment]
Hi Ralph,

Thanks for the kind words.

As for a roadmap, there is not really anything formal. I'm happy with the overall architecture and don't have any plans to change it. Some things that come to mind are:

* Keep current with the IIIF Image API
* Improve support for >8-bit source images
* Continue to field feature requests and bug reports
* Misc. minor features/improvements as they come up

There are also some older issues in the tracker that remain there because of an unfavorable cost/benefit ratio. But, maybe some day.

**Comment by Ra1phM** [comment]
All right, thanks for your answer :)
